#maven plugin help mojo generation informations
#Fri May 09 12:00:29 WEST 2025
destinationDirectory=C\:\\Users\\elmehdi.tazi\\DEV\\PFE\\jsp-thymeleaf-toolkit\\jsp2tl-maven-plugin\\target\\generated-sources\\plugin
helpPackageName=
