#maven plugin help mojo generation informations
#Sun May 11 00:58:08 WEST 2025
destinationDirectory=C\:\\Users\\elmehdi.tazi\\DEV\\PFE\\jsp-thymeleaf-toolkit\\jsp2tl-maven-plugin\\target\\generated-sources\\plugin
helpPackageName=
